version: '3.7'
services:
  app-server:
    image: pravallika07/employeeportal_app-server
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend

  app-client:
    image: pravallika07/employeeportal_app-client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app-server
    environment:
      - "REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}"
    networks:
      - frontend

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
