name: CI for Spring Boot App
on:
  push:
    branches: [ master ]
jobs:
  Spring:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
        
  React:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: |
          cd src/main/java/com/example/employeePortal/employee-portal-react
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: src/main/java/com/example/employeePortal/employee-portal-react/package-lock.json

      - name: Run npm install
        run: |
          cd src/main/java/com/example/employeePortal/employee-portal-react
          npm install
